USE [master]
GO

/****** Object:  Database [NORTHWND]    Script Date: 9/19/2019 6:01:43 PM ******/
CREATE DATABASE [NORTHWND]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Northwind', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NORTHWND.MDF' , SIZE = 5184KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Northwind_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NORTHWND_log.ldf' , SIZE = 3840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [NORTHWND] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NORTHWND].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [NORTHWND] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NORTHWND] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NORTHWND] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NORTHWND] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NORTHWND] SET ARITHABORT OFF 
GO

ALTER DATABASE [NORTHWND] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NORTHWND] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NORTHWND] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NORTHWND] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NORTHWND] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NORTHWND] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NORTHWND] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NORTHWND] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NORTHWND] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NORTHWND] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NORTHWND] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NORTHWND] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NORTHWND] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NORTHWND] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NORTHWND] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NORTHWND] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NORTHWND] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NORTHWND] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NORTHWND] SET  MULTI_USER 
GO

ALTER DATABASE [NORTHWND] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [NORTHWND] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NORTHWND] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NORTHWND] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NORTHWND] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NORTHWND] SET QUERY_STORE = OFF
GO

USE [NORTHWND]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NORTHWND] SET  READ_WRITE 
GO

